name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Required for OpenID Connect authentication with PyPI

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: abatilo/actions-poetry@v2

      - name: Build release distributions
        run: poetry build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  testpypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ucc/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: testpypi-publish
    if: github.ref == 'refs/heads/main'  # Ensures only main branch triggers PyPI deploy
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/ucc/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
