# This workflow will install Python dependencies, run tests using poetry.
# It can be tested locally using https://github.com/nektos/act with the command `act push --container-architecture linux/amd64 -j test`

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies & ucc
        run: poetry install

      - name: Run linter
        run: poetry run ruff check

      - name: Run formatter check
        run: poetry run ruff format --check

      - name: Run tests
        run: poetry run pytest ucc --verbose
