name: Run Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-benchmarks:
    runs-on: ucc-benchmarks-8-core

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure the full history is fetched for branch operations

      # Checkout the correct branch
      - name: Checkout the branch
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          echo "Checking out branch: $BRANCH_NAME"
          git checkout $BRANCH_NAME

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ucc-benchmark .

      # Run the benchmarks in the Docker container
      - name: Run benchmarks
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/benchmarks/results:/ucc/benchmarks/results \
            ucc-benchmark bash -c "source /venv/bin/activate && ./benchmarks/scripts/small_test.sh 8 && python ./benchmarks/scripts/generate_latest_benchmark_plot.py"

      # Commit and push benchmark results using a dedicated action
      - name: Commit and push results
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Update benchmark results"
          add: "benchmarks/*"
          push: true
